import Config

# Do not print debug messages in production
config :logger, level: :info

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :senpai_web, SenpaiWeb.Endpoint,
  url: [host: "example.com", port: 80],
  # Runtime production configuration, including reading
  # of environment variables, is done on config/runtime.exs.
  cache_static_manifest: "priv/static/cache_manifest.json"
